Projects - Controllers, routes and validations - GET & POST
BaSP-m2022/martina-trackgenix-server pull request #14
Opened 2022-05-17 16:36 UTC by x-Ramses-x

This functionality allows you to:
View all saved projects and add projects to a server.

2022-05-17 17:28 UTC, martumoser requested changes

2022-05-17 17:28 UTC, martumoser commented on postman_collection.json
>  {
Estás borrando toda la colección agregada por Evelyn. Deberías conservar la que ya está y agregar la correspondiente a tu recurso.

2022-05-17 17:28 UTC, martumoser commented on src/models/Projects.js
> +const projectsSchema = new Schema({
Utilizar project en singular

2022-05-17 17:28 UTC, martumoser commented on src/models/Projects.js
> +const projectsSchema = new Schema({
Utilizar project en singular

2022-05-17 17:28 UTC, martumoser commented on src/controllers/projects.js
> +import ProjectsSchema from '../models/Projects';
Reemplazar por: `import Project from '../models/Projects';`

2022-05-17 17:28 UTC, martumoser commented on src/controllers/projects.js
> +import ProjectsSchema from '../models/Projects';
Reemplazar por: `import Project from '../models/Projects';`

2022-05-17 17:28 UTC, martumoser commented on src/routes/index.js
> -import adminRoutes from './admins';
Deberías conservar lo que venia de master y agregar tus cambios. La linea 2, 6 y 7 no deberian ser borradas

2022-05-18 01:20 UTC, Julian25 commented on src/controllers/projects.js
> +    await project.save();
No es necesario especificatr cada unos de los campos(linea 18 a 27).  Una manera mas simple y ordenado de hacerlo seria poner :
const project = req.body.
Ademas, en lugar de .save(), denerias cambiarlo por create().
Ejmemplo:
const project = req.body;
const newProject = await Project.create(project);

2022-05-18 01:20 UTC, Julian25 commented on src/controllers/projects.js
> +      message: 'An error has occured',
Aca,  para cumplir con el formato de respuesta solicitado para la problematica, deberias poner:
return res.status(400).json({
      message: 'An error has ocurred',
      data: undefined,
      error: true,

2022-05-18 20:09 UTC, negrojcb commented on postman_collection.json
> -  }
creo q va una coma ahi

2022-05-18 20:13 UTC, negrojcb commented on src/controllers/projects.js
> +  } catch (err) {
l arespuesta deberia tener este fomatoreturn res.status(200).json({
      message: 'fsdfsd',
      data: sdsdasd,
      error: false/true,

2022-05-18 20:18 UTC, martumoser requested changes

2022-05-18 20:18 UTC, martumoser commented on postman_collection.json
> -  }
No es necesaria la coma y esa parte del archivo se eliminó

2022-05-18 20:18 UTC, martumoser commented on src/validations/projects.js
> +  const employeeProjectSchema = Joi.object({
Reemplazar por employeeSchema

2022-05-18 20:18 UTC, martumoser commented on src/validations/projects.js
> +
Eliminar este espacio

2022-05-18 20:40 UTC, negrojcb commented on src/controllers/projects.js
> +};
Faltaria un getProjectsById para que quede consistente con lo que hicimos todos

2022-05-18 20:41 UTC, negrojcb commented on src/routes/projects.js
> +  .get('/', projectsController.getAllProjects)
aca tambien se deberia agregar la ruta para traer un project by id

2022-05-18 20:42 UTC, negrojcb commented on src/validations/projects.js
> +
No deberia haber un salto de linea

2022-05-18 21:53 UTC, martumoser approved these changes
PR APPROVE

2022-05-18 21:53 UTC, merged