Feature/tg 8/projects
BaSP-m2022/martina-trackgenix-server pull request #15
Opened 2022-05-17 19:42 UTC by laura-brussa12

Here you can edit a project or delete one

2022-05-17 23:18 UTC, Evelyn-Heredia commented on src/controllers/projects.js
> +import Projects from '../models/Projects';
Para tener consistencia con el resto del equipo podrías usar `Project `en vez de Projects. Recordar cambiar todas las instancias que aparecen en este file y además cuando lo exportas en en el file de models.

2022-05-17 23:19 UTC, Evelyn-Heredia commented on src/controllers/projects.js
> +// eslint-disable-next-line consistent-return
Eliminar este comentario de eslint

2022-05-17 23:21 UTC, Evelyn-Heredia commented on src/controllers/projects.js
> +/* if (!result) {
Eliminar este comentario

2022-05-17 23:23 UTC, Evelyn-Heredia commented on src/controllers/projects.js
> +      return res.status(404).json({
Agregar `data` para tener consistencia con lo establecido en la problemática

2022-05-17 23:26 UTC, Evelyn-Heredia commented on src/models/Projects.js
> +module.exports = mongoose.model('Projects', projectsSchema);
Recordar poner en singular `Project`

2022-05-17 23:27 UTC, Evelyn-Heredia commented on src/models/Projects.js
> +const projectsSchema = new mongoose.Schema({
Revisar la indentación del Schema

2022-05-18 22:14 UTC, Julian25 commented on src/models/Projects.js
> +  id: String,
Linea 4 a 18, agregar required en cada propiedad

2022-05-19 12:07 UTC, martumoser requested changes

2022-05-19 12:07 UTC, martumoser commented on src/controllers/projects.js
> +const upDateProject = async (req, res) => {
Reemplazar por updateProject

2022-05-19 12:07 UTC, martumoser commented on src/routes/projects.js
> +import ProjectsValidation from '../validations/projects';
Utilizar camelCase: projectsController y projectsValidation

2022-05-19 15:37 UTC, martumoser approved these changes
PR APPROVE

2022-05-19 15:37 UTC, merged