BaSP-TG: Employee routes, controllers and validations
BaSP-m2022/martina-trackgenix-server pull request #16
Opened 2022-05-17 20:59 UTC by MartinDidoli

- Endpoints logic updated + HTTP status code
- New Schema for the employees done
- Joi Validations created
- Postman Collection created
- JSON file deleted

2022-05-17 22:03 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +import EmployeeModel from '../models/Employees';
Este import tiene que coincidir que con el nombre que estas usando en el export de models. Deberias reemplazar esta linea por import `Employee from '../models/Employees';`

2022-05-17 22:04 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +    const AllEmployees = await EmployeeModel.find({});
Deberías dejar una línea después de declarar la constante en la línea 5

2022-05-17 22:08 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +    return res.status(400).json({
El HTTP status code aquí debería ser **404**, porque la request se supone que esta bien hecha pero el id no existe en la base de datos

2022-05-17 22:10 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +    return res.status(404).json({
El HTTP status code aquí debería ser **400**, porque la request se supone que esta mal hecha

2022-05-17 22:12 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +    const oneEmployee = new EmployeeModel({
No es necesario especificar cada uno de los campos. Una forma más simple y ordenada de hacerlo es borrar desde la línea 46 hasta la 53 y definir `const employeeData = req.body;`

2022-05-17 22:16 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +    const result = await oneEmployee.save();
Podés usar .create() para crear un nuevo employee y .save() para editarlo. Por lo tanto,podrías tener:
```
const newEmployee = await Employee.create(employeeData);
    res.status(201).json({
      message: "Employee created",
      data: newEmployee,
      error: false,
    });

```

2022-05-17 22:17 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +    return res.status(404).json({
Ídem línea 36

2022-05-17 22:19 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +      return res.status(400).json({
Ídem línea 30

2022-05-17 22:20 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +    }
Dejar una línea antes de definir la constante

2022-05-17 22:24 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +      return res.status(400).json({
Ídem línea 30

2022-05-17 22:26 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +      msg: 'Employee requested was deleted',
El error 204 no muestra mensaje, por lo tanto podés borrar las líneas 122,123 y 124

2022-05-17 22:28 UTC, Evelyn-Heredia commented on src/controllers/employees.js
> +      data: undefined,
En la data podes mandar `error`

2022-05-17 22:32 UTC, Evelyn-Heredia commented on src/models/Employees.js
> +const employeeSchema = new mongoose.Schema({
Dar un enter antes de la llave, para que baje a la línea 3

2022-05-17 22:34 UTC, Evelyn-Heredia commented on src/routes/employees.js
> +router.put('/:id', employeesController.editEmployee);
Agregar la validación `employeesValidation,`

2022-05-17 22:35 UTC, Evelyn-Heredia commented on src/validations/employees.js
> +  });
Dejar una línea entre las líneas 11 y 12

2022-05-18 17:28 UTC, martumoser requested changes
Falta actualizar la coleccion de postman

2022-05-18 17:28 UTC, martumoser commented on src/controllers/employees.js
> +    const AllEmployees = await Employee.find({});
Usar camelCase para el nombre de la constante

2022-05-18 17:28 UTC, martumoser commented on src/validations/employees.js
> +  const employeeTestSchema = Joi.object({
Reemplazar por employeeSchema

2022-05-18 17:53 UTC, martumoser approved these changes

2022-05-18 18:10 UTC, martumoser approved these changes

2022-05-18 18:10 UTC, merged