Feature/ 12/super adm test
BaSP-m2022/martina-trackgenix-server pull request #20
Opened 2022-05-24 03:13 UTC by lautaro23

2022-05-24 19:44 UTC, martumoser requested changes

2022-05-24 19:44 UTC, martumoser commented on src/tests/super-admin.test.js
> +      firstName: 'Lautaro',
Esto lo podes declarar en una constante por fuera asi queda el codigo mas limpio. Podrias agregar antes del describe:
```
const mockReqBody = {
      firstName: 'Lautaro',
      lastName: 'Acosta',
      email: 'lautaroeacosta23@gmail.com',
      password: 'test12345',
      active: true,
 }
```
y en la response le mandas esa variable: 
`
const response = await request(app).post('/super-admins').send(mockReqBody);
    `

2022-05-24 22:59 UTC, Julian25 commented on src/tests/super-admin.test.js
> +    expect(response.body.message).toEqual('super Admin created');
podrias agregar: expect(response.body.error).toBeFalsy();

2022-05-24 22:59 UTC, Julian25 commented on src/tests/super-admin.test.js
> +    expect(response.status).toBe(400);
podrias agregar: expect(response.body.error).toBeTruthy()

2022-05-24 22:59 UTC, Julian25 commented on src/tests/super-admin.test.js
> +  test('should not create super admin', async () => {
aca agrega "if the body request is empty"

2022-05-24 22:59 UTC, Julian25 commented on src/tests/super-admin.test.js
> +    expect(response.status).toBe(400);
podrias agregar: expect(response.body.error).toBeTruthy()

2022-05-24 22:59 UTC, Julian25 commented on src/tests/super-admin.test.js
> +describe('GET and GET BY ID /:id', () => {
agregar "and error: false"

2022-05-24 22:59 UTC, Julian25 commented on src/tests/super-admin.test.js
> +    expect(response.status).toBe(200);
aca agregar expect(response.error).toBeFalsy(); y te ahorras el hecho de hacer dos test

2022-05-24 22:59 UTC, Julian25 commented on src/tests/super-admin.test.js
> +    expect(response.status).toBe(200);
aca agregar expect(response.error).toBeFalsy(); y te ahorras el hecho de hacer dos test

2022-05-24 22:59 UTC, Julian25 commented on src/tests/super-admin.test.js
> +    expect(response.status).toBe(201);
juntar este test con el siguiente

2022-05-25 00:08 UTC, martumoser requested changes

2022-05-25 00:08 UTC, martumoser commented on src/tests/super-admin.test.js
> +
Este test está repetido

2022-05-25 00:08 UTC, martumoser commented on src/tests/super-admin.test.js
> +    const response = await request(app).put(`/super-admins/${superAdmId}`).send(mockReqBody);
Estas usando el mismo mock para el post que para el update, deberian ser dos mocks distintos pq en el update vos editas

2022-05-25 00:08 UTC, martumoser commented on src/tests/super-admin.test.js
> +    const response = await request(app).post('/super-admins').send({
Podrias poner esto en una constante aparte como hiciste con el body del post

2022-05-25 00:08 UTC, martumoser commented on src/tests/super-admin.test.js
> +    });
Idem comentario anterior

2022-05-25 16:27 UTC, martumoser approved these changes
PR APPROVE

2022-05-25 16:27 UTC, merged