BaSP-TG: unit test for Tasks
BaSP-m2022/martina-trackgenix-server pull request #23
Opened 2022-05-24 15:57 UTC by negrojcb

Work made on this branch

- Data base mocked

- Create seed folder with tasks schema

- Endpoints tested: POST, GET, GET BY ID, PUT AND DELETE

2022-05-24 22:21 UTC, lautaro23 commented on src/tests/tasks.test.js
> +      description: 'convallis nulla neque libero convallis eget eleifend',
Esto lo podes declarar en una constante por fuera asi queda el codigo mas limpio. Podrias agregar antes del describe:
```suggestion
      const mockReqBody = { description: 'convallis nulla neque libero convallis eget eleifend'}
```
y en la response le mandas esa variable:
``const response = await request(app).post('/super-admins').send(mockReqBody);
```

2022-05-24 22:26 UTC, lautaro23 commented on src/tests/tasks.test.js
> +      description: 'convallis nulla neque libero convallis eget eleifend',
Esto lo podes declarar en una constante por fuera asi queda el codigo mas limpio. Podrias agregar antes del describe:
`const mockReqBody = description: 'convallis nulla neque libero convallis eget eleifend'`
y en la response le mandas esa variable:
`const response = await request(app).post('/super-admins').send(mockReqBody);`

2022-05-25 01:59 UTC, martumoser requested changes

2022-05-25 01:59 UTC, martumoser commented on src/tests/tasks.test.js
> +describe('DELETE method tests', () => {
Podrias incluir un test que testee el error 404 cuando se pasa un wrong id

2022-05-25 01:59 UTC, martumoser commented on src/tests/tasks.test.js
> +      description: 'convallis nulla neque libero convallis eget eleifend',
No marcar como resuelto si no se implementó la corrección y si no se va a implementar por algun motivo dejarlo explicado en un comentario

2022-05-25 16:34 UTC, martumoser approved these changes
PR APPROVE

2022-05-25 16:34 UTC, merged