BaSP-TG-91: Check entity employee
BaSP-m2022/martina-trackgenix-server pull request #28
Opened 2022-06-27 20:43 UTC by javierbiselli

- [ ] Check Schema
- [ ] Check controllers and endpoints
Also modified validations to match frontend's

2022-06-28 03:15 UTC, LucianoAlarcon approved these changes
🚀🚀

2022-06-28 03:22 UTC, SebastianCocci approved these changes

2022-06-28 23:41 UTC, LucasPrat1 approved these changes

2022-06-29 00:49 UTC, LucasPrat1 requested changes

2022-06-29 00:49 UTC, LucasPrat1 commented on src/controllers/employees.js
> +    return res.status(200).json({
debería ser status 204

2022-06-29 00:49 UTC, LucasPrat1 commented on src/tests/employees.test.js
> +    expect(employeeDelete.statusCode).toBe(200);
debería ser 204

2022-06-29 12:18 UTC, LucasPrat1 approved these changes

2022-06-29 12:18 UTC, merged