TG-115: fix endpoints super admin
BaSP-m2022/martina-trackgenix-server pull request #34
Opened 2022-07-07 23:39 UTC by EzeRocco

- [ ] Register superAdmin whit firebase.
- [ ]  add firebaseUid to schema.
- [ ] Update validations.

2022-07-08 00:00 UTC, JuanMornik commented on src/tests/super-admin.test.js
> +  test.skip('should create an super admin, return error false and message super Admin created', async () => {
por que skipeas este test?

2022-07-08 00:55 UTC, JuanMornik requested changes

2022-07-08 00:55 UTC, JuanMornik commented on src/controllers/super-admins.js
> +      message: 'An error occurred in the Get all method of Super Admin',
Estaría bueno reemplazar los mensajes hardcodeados por el que te trae la response

2022-07-11 13:47 UTC, NancyCima approved these changes

2022-07-11 13:47 UTC, LucianoAlarcon approved these changes

2022-07-11 13:52 UTC, merged